[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "probe-rs run --chip nRF9160_xxAA"
runner = [
    "probe-rs",
    "run",
    "--chip=nRF52840_xxAA",
    # "--always-print-stacktrace",
    "--protocol=swd",
    # "--log-format={t} {[{L}]%bold} {s}  {{c} {ff}:{l:1}%dimmed}",
]

[build]
target = "thumbv7em-none-eabihf"
# target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "trace"
